version: 2.1

orbs:
   xmatters: xm-sandbox/hello-world@0.0.1

workflows:
   "testing the xM Thingy":
      jobs:
         - hello-world/notify:
                 xm_url: ${XM_URL}
                 someparm_1: "Some value?"
    
