version: 2.1

orbs:
   xmatters: xm-sandbox/xmatters-orb@0.0.10

jobs:
   build:
      docker: 
         - image: circleci/node:4.8.2
      steps:
         - run:
            name: env?
            command: |
                    echo $XM_URL
         - xmatters/notify_raw:
            json_payload: '{"properties": { 
                  "author":     "'${CIRCLE_PROJECT_USERNAME}'",
                  "project":    "'$CIRCLE_PROJECT_REPONAME'",
                  "branch":     "'${CIRCLE_BRANCH}'",
                  "commit":     "'${CIRCLE_SHA1}'",
                  "build":      "'${CIRCLE_BUILD_NUM}'",
                  "build_url":  "'${CIRCLE_BUILD_URL}'",
                  "job":        "'${CIRCLE_JOB}'",
                  "job_status": "'${XM_BUILD_STATUS}'"
               },
               "recipients": [{"id": "tdepuy"}]
               }'
