version: 2.1

orbs:
   xmatters: xm-sandbox/xmatters-orb@0.0.6

jobs:
   build:
      docker: 
         - image: circleci/node:4.8.2
      steps:
         - run:
            name: Check current version of node
            command: node -v
         - run:
            name: env?
            command: |
                    echo $XM_URL
                    env
         - xmatters/notify:
            author: "Jo mama"
            project: "that one project"
