version: 2.1

orbs:
   xmatters: xm-sandbox/xmatters-orb@0.0.1

jobs:
   build:
      docker: 
         - image: circleci/node:4.8.2
      steps:
         - run:
            name: Check current version of node
            command: node -v
         - xmatters/notify:
            xm_url: ${XM_URL}
            someparm_1: "Some value?"
            author: "Jo mama"
            project: "that one project"
