version: 2.1

orbs:
   xmatters: xmatters/xmatters-orb@1.0.2

jobs:
   build:
      docker: 
         - image: circleci/node:4.8.2
      steps:
         - run:
            name: env?
            when: on_fail
            command: |
                    echo $XM_URL
                    env
         - xmatters/notify:
            author: "Jo mama"
            project: "that one project"
