version: 2.1

orbs:
   xmatters: xm-sandbox/xmatters-orb@0.0.7

jobs:
   build:
      docker: 
         - image: circleci/node:4.8.2
      steps:
         - run:
            name: Fail!
            command: |
               set +e
               exit 1
         - run:
            name: env?
            command: |
                    echo $XM_URL
                    env
         - xmatters/notify:
            author: "Jo mama"
            project: "that one project"
