version: 2.1

orbs:
   xmatters: xm-sandbox/hello-world@0.0.1

jobs:
   "testing the xM Thingy":
      steps:
         - xm-sandbox/notify:
                 xm_url: ${XM_URL}
                 someparm_1: "Some value?"
    
