version: 2.1

orbs:
  xmatters: xmatters/xmatters-orb@1.0.2

jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - run: echo "Building building building."

  request-approval:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - xmatters/notify

  # hold:
  #   docker:
  #     - image: circleci/node:4.8.2
  #   steps:
  #     - run: echo "Holding for approval"

  deploy-stuff:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "Deploy stuff here"

workflows:
  build-test-and-approval-deploy:
    jobs:
      - build
      - request-approval:
          type: approval
          requires:
            - build
      - deploy-stuff:
          requires:
            - request-approval